export const Strings = {
  appName: 'Bizmanto',
  welcome: 'Welcome Back!',
  login: 'Login',
  logout: 'Logout',
  dashboard: 'Dashboard',
  finance: 'Finance',
  balance: 'Total Balance',
  transactions: 'Recent Transactions',
  settings: 'Settings',
  profile: 'Profile',
  email: 'Email Address',
  password: 'Password',
  submit: 'Submit',
  cancel: 'Cancel',
  error: 'Something went wrong',
  loading: 'Loading...',
  home: 'Home',
  reports: 'Reports',
  username: 'Username',
  loginSubtitle: 'Sign in to continue',
  viewAll: 'VIEW ALL',
  thisMonth: 'THIS MONTH',
  bankAccounts: 'BANK ACCOUNTS',
  cashAccounts: 'CASH ACCOUNTS',
  receivablesPayables: 'Current Receivables / Payables',
  receivables: 'Receivables',
  payables: 'Payables',
  recentActivity: 'Recent Activity',
  enterpriseFinance: 'Bussiness Management Tool',
  connecting: 'Connecting...',
  loginEnterprise: 'Login',
  poweredBy: 'Powered by Aizeck',
  azureProtected: 'Azure AD B2C Protected',
  userProfile: 'User: user@bizmanto.com',
  periodSettings: 'Period Settings',
  performancePresets: 'PERFORMANCE PRESETS',
  today: 'TODAY',
  thisWeek: 'THIS WEEK',
  lastWeek: 'LAST WEEK',
  lastMonth: 'LAST MONTH',
  thisQuarter: 'THIS QUARTER',
  fiscalYear: 'FISCAL YEAR',
  select: 'SELECT',
  
  // Quick Actions
  transfer: 'Transfer',
  topUp: 'Top-up',
  billPay: 'Bill Pay',
  scan: 'Scan',

  // Performance Card
  netProfit: 'NET PROFIT',
  revenue: 'REVENUE',
  expenses: 'EXPENSES',
  performance: 'PERFORMANCE',

  // Dashboard
  todaysRecords: "Today's Records",
};
